import type { Metadata } from 'next';
import { Inter, Roboto_Condensed } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

const robotoCondensed = Roboto_Condensed({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Lisp Solutions',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={robotoCondensed.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
