import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ReactNode } from 'react';

const robotoCondensed = Roboto_Condensed({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Lisp Solutions',
  description: 'Generated by create next app',
  authors: [
    {
      name: 'Alexandre Costa Belettini',
      url: 'https://www.linkedin.com/in/alexandrexyz/'
    },
    {
      name: 'Artur Campos',
      url: 'https://www.linkedin.com/in/artur-campos-19442a286/'
    }
  ],
  keywords: ['lisp solution', 'solutions', 'business solution'],
  themeColor: [
    {
      color: '#fff',
    },
    {
      color: '#074ca1'
    }
  ],
};

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={robotoCondensed.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
